# Generated by Django 4.0.3 on 2022-06-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartapp_User',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('regdNo', models.IntegerField(primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
                ('eMail', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('regdNo', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('rollNo', models.IntegerField()),
                ('branch', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('dob', models.IntegerField()),
                ('eMail', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
